// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModellenBureau.API.Models;

namespace ModellenBureau.API.Migrations
{
    [DbContext(typeof(MBDbContext))]
    [Migration("20210209132003_12")]
    partial class _12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ModellenBureau.Main.Shared.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("BtwNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KvkNummer")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Achternaam = "Janssen",
                            Adres = "Verdilaan 107",
                            AppUserId = 1,
                            BtwNummer = "NL123456789B01",
                            KvkNummer = 12345678,
                            Logo = "",
                            Postcode = "4384 LG",
                            Stad = "Vlissingen",
                            Verified = false,
                            Voornaam = "Klaas"
                        },
                        new
                        {
                            CustomerID = 2,
                            Achternaam = "Gerritsen",
                            Adres = "Uiterburen 13",
                            AppUserId = 2,
                            BtwNummer = "NL234567890B02",
                            KvkNummer = 23456789,
                            Logo = "",
                            Postcode = "9636 EC",
                            Stad = "Groningen",
                            Verified = false,
                            Voornaam = "Angelina"
                        });
                });

            modelBuilder.Entity("ModellenBureau.Main.Shared.PhotoModel", b =>
                {
                    b.Property<int>("PhotoModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("Bovenwijdte")
                        .HasColumnType("int");

                    b.Property<string>("Fotos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Geslacht")
                        .HasColumnType("int");

                    b.Property<int>("Heupwijdte")
                        .HasColumnType("int");

                    b.Property<int>("Leeftijd")
                        .HasColumnType("int");

                    b.Property<int>("Lengte")
                        .HasColumnType("int");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Taillewijdte")
                        .HasColumnType("int");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoModelID");

                    b.ToTable("PhotoModels");

                    b.HasData(
                        new
                        {
                            PhotoModelID = 1,
                            Achternaam = "Vermeulen",
                            Adres = "Leemwierde 40",
                            AppUserId = 3,
                            Bovenwijdte = 90,
                            Fotos = "",
                            Geboortedatum = new DateTime(1985, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Geslacht = 1,
                            Heupwijdte = 90,
                            Leeftijd = 35,
                            Lengte = 178,
                            Postcode = "1353 LT",
                            Stad = "Almere",
                            Taillewijdte = 61,
                            Verified = false,
                            Voornaam = "Fleur"
                        },
                        new
                        {
                            PhotoModelID = 2,
                            Achternaam = "de Wit",
                            Adres = "Oregondreef 102",
                            AppUserId = 4,
                            Bovenwijdte = 86,
                            Fotos = "",
                            Geboortedatum = new DateTime(1991, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Geslacht = 1,
                            Heupwijdte = 87,
                            Leeftijd = 29,
                            Lengte = 175,
                            Postcode = "3565 BG",
                            Stad = "Utrecht",
                            Taillewijdte = 59,
                            Verified = false,
                            Voornaam = "Lynn"
                        },
                        new
                        {
                            PhotoModelID = 3,
                            Achternaam = "Peters",
                            Adres = "Dollardstraat 2",
                            AppUserId = 5,
                            Bovenwijdte = 101,
                            Fotos = "",
                            Geboortedatum = new DateTime(1980, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Geslacht = 0,
                            Heupwijdte = 99,
                            Leeftijd = 41,
                            Lengte = 184,
                            Postcode = "1826 CS",
                            Stad = "Alkmaar",
                            Taillewijdte = 81,
                            Verified = false,
                            Voornaam = "Luuk"
                        },
                        new
                        {
                            PhotoModelID = 4,
                            Achternaam = "Meijer",
                            Adres = "Martin Luther Kinglaan 93",
                            AppUserId = 6,
                            Bovenwijdte = 100,
                            Fotos = "",
                            Geboortedatum = new DateTime(1990, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Geslacht = 0,
                            Heupwijdte = 100,
                            Leeftijd = 30,
                            Lengte = 185,
                            Postcode = "1111 LK",
                            Stad = "Diemen",
                            Taillewijdte = 81,
                            Verified = false,
                            Voornaam = "Stefan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
